[package]
name = "sand"
version = "0.1.0"
authors = ["cyto <akthoamaaa14@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
sdl2 = { version = "0.34.5", features = ["bundled", "static-link", "ttf"] }
rand = "0.7.3"